import { useEffect, useMemo, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { motion, AnimatePresence } from "motion/react";
import { createClient } from "@supabase/supabase-js";
import { Activity, AlertTriangle, Baby, CalendarDays, Camera, Check, ChevronRight, ClipboardList, Library, Plus, ShieldCheck, Sparkles, Sprout, X } from "lucide-react";

const supabase=createClient("https://vqxzrydqnlpxyjafjdoh.supabase.co","sb_publishable_Pn-dEaqu0oWYJ8eK8OgUAg_PPORfQFF");
const demoMeals=[{id:"demo-1",food:"苹果泥",amount_grams:30,eaten_at:"2026-07-13T09:20:00+02:00",reaction:"很喜欢",note:"无异常",asset:"/assets/apple-puree.png"},{id:"demo-2",food:"婴儿米糊",amount_grams:45,eaten_at:"2026-07-13T12:10:00+02:00",reaction:"愿意尝试",note:"无异常",asset:"/assets/rice-cereal.png"}];
const foodAssets={苹果:"/assets/apple-puree.png",米糊:"/assets/rice-cereal.png",南瓜:"/assets/pumpkin.png"},pendingKey="baby-meals-pending-v2",cacheKey="baby-meals-cache-v2";
const assetFor=food=>Object.entries(foodAssets).find(([name])=>food.includes(name))?.[1]||"/assets/rice-cereal.png";
const readLocal=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const avatarKey="elnaz-avatar-local-v1";
const prepareAvatar=file=>new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onerror=reject;reader.onload=()=>{img.onload=()=>{const size=512,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d"),side=Math.min(img.width,img.height),sx=(img.width-side)/2,sy=(img.height-side)/2;ctx.drawImage(img,sx,sy,side,side,0,0,size,size);canvas.toBlob(blob=>blob?resolve({blob,dataUrl:canvas.toDataURL("image/webp",.84)}):reject(new Error("图片处理失败")),"image/webp",.84)};img.src=reader.result};reader.readAsDataURL(file)});

function Header({online,onCalendar}){const[photo,setPhoto]=useState(()=>localStorage.getItem(avatarKey)||"/assets/baby-avatar.png"),[status,setStatus]=useState("");useEffect(()=>{(async()=>{if(!navigator.onLine)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:profile}=await supabase.from("baby_profiles").select("avatar_path").eq("user_id",user.id).maybeSingle();if(profile?.avatar_path){const{data}=await supabase.storage.from("baby-avatars").download(profile.avatar_path);if(data)setPhoto(URL.createObjectURL(data))}})()},[]);const change=async event=>{const file=event.target.files?.[0];if(!file)return;try{const{blob,dataUrl}=await prepareAvatar(file);setPhoto(dataUrl);localStorage.setItem(avatarKey,dataUrl);if(!navigator.onLine){setStatus("离线已保存");return}const{data:{user}}=await supabase.auth.getUser();if(!user){setStatus("登录后同步");return}const path=`${user.id}/elnaz-avatar.webp`;const{error}=await supabase.storage.from("baby-avatars").upload(path,blob,{contentType:"image/webp",upsert:true});if(error)throw error;await supabase.from("baby_profiles").upsert({user_id:user.id,baby_name:"Elnaz",avatar_path:path,updated_at:new Date().toISOString()});setStatus("头像已同步")}catch{setStatus("保存失败")}};return <header className="baby-header"><label className="avatar-editor" aria-label="更换 Elnaz 的头像"><img className="baby-avatar" src={photo} alt="Elnaz 的头像"/><span><Camera size={13}/></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={change}/></label><div className="baby-identity"><div><strong>Elnaz</strong><span>5个月</span></div><p>2026-07-13 · 星期一</p></div><button className="calendar-button" onClick={onCalendar} aria-label="查看日历"><CalendarDays size={20}/></button><div className="family-sync" aria-label={online?"爸妈已同步":"离线记录中"}><span><Baby size={16}/></span><i/><span className="parent-two"><Baby size={16}/></span><small>{status||(online?"爸妈已同步":"离线记录中")}</small></div></header>}
function HealthStrip(){return <section className="health-block"><h2>身体反应 / 过敏状态</h2><div className="health-strip">{[[ShieldCheck,"无异常"],[Sparkles,"皮肤正常"],[Activity,"消化正常"]].map(([Icon,label])=><div key={label}><Icon/><span>{label}</span></div>)}</div></section>}
function MealTimeline({meals}){return <section className="meal-section"><div className="section-title"><h2>今日记录</h2><button>按时间 <ChevronRight size={16}/></button></div><div className="timeline">{meals.map((meal,index)=><motion.article className="meal-row" key={meal.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.08}}><time>{new Date(meal.eaten_at).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})}</time><span className="timeline-dot"/><img src={meal.asset||assetFor(meal.food)} alt=""/><div className="meal-copy"><h3>{meal.food}</h3><p><b>{meal.amount_grams}克</b><span>{meal.reaction}</span></p></div><div className="meal-safe"><Check size={15}/><span>{meal.note||"无异常"}</span></div><ChevronRight className="meal-chevron" size={20}/></motion.article>)}</div><button className="view-all">查看全部记录 <ChevronRight size={17}/></button></section>}

function AddMealDialog({open,onOpenChange,onSave}){const[food,setFood]=useState("苹果泥"),[amount,setAmount]=useState(30),[time,setTime]=useState("14:30"),[reaction,setReaction]=useState("很喜欢"),[body,setBody]=useState("无异常");return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="meal-sheet"><div className="sheet-grabber"/><div className="sheet-head"><div><Dialog.Title>记录一餐</Dialog.Title><Dialog.Description>几步就能记好，常用选项已为你准备。</Dialog.Description></div><Dialog.Close className="icon-button"><X size={20}/></Dialog.Close></div><form onSubmit={e=>{e.preventDefault();onSave({food,amount_grams:Number(amount),time,reaction,note:body})}}><label>吃了什么<select value={food} onChange={e=>setFood(e.target.value)}><option>苹果泥</option><option>婴儿米糊</option><option>南瓜泥</option><option>胡萝卜泥</option></select></label><div className="form-grid"><label>分量（克）<input type="number" min="1" max="1000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>时间<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><Choices title="喜欢程度" value={reaction} setValue={setReaction} items={["很喜欢","愿意尝试","一般般","不太喜欢"]}/><Choices title="身体反应" value={body} setValue={setBody} items={["无异常","皮肤反应","消化不适","需要观察"]}/><button className="save-button" type="submit"><Check size={19}/>保存这餐</button></form></Dialog.Content></Dialog.Portal></Dialog.Root>}
function Choices({title,value,setValue,items}){return <fieldset><legend>{title}</legend><div className="choice-row">{items.map(x=><button type="button" className={value===x?"selected":""} onClick={()=>setValue(x)} key={x}>{x}</button>)}</div></fieldset>}
function AuthDialog({open,onSignedIn}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState("");const login=async e=>{e.preventDefault();setMessage("正在登录…");const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage("登录失败，请检查邮箱和密码");else{setMessage("");onSignedIn(data.user)}};const signup=async()=>{setMessage("正在创建家庭账号…");const{error}=await supabase.auth.signUp({email,password});setMessage(error?error.message:"请打开邮箱中的确认链接，然后回来登录。");};return <Dialog.Root open={open}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="auth-card"><img src="/assets/baby-avatar.png" alt=""/><Dialog.Title>欢迎来到宝贝食光</Dialog.Title><Dialog.Description>登录后，你和家人可以随时同步 Elnaz 的辅食记录。</Dialog.Description><form onSubmit={login}><label>邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>密码<input type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="save-button" type="submit">登录</button><button className="signup-link" type="button" onClick={signup}>第一次使用？创建家庭账号</button><p className="auth-message">{message}</p></form></Dialog.Content></Dialog.Portal></Dialog.Root>}

function App(){const[meals,setMeals]=useState(()=>readLocal(cacheKey,demoMeals)),[sheetOpen,setSheetOpen]=useState(false),[authOpen,setAuthOpen]=useState(false),[online,setOnline]=useState(navigator.onLine),[notice,setNotice]=useState(""),[avatar,setAvatar]=useState(()=>localStorage.getItem(avatarKey)||"/assets/baby-avatar.png");const total=useMemo(()=>meals.reduce((sum,m)=>sum+Number(m.amount_grams),0),[meals]);
const sync=async()=>{if(!navigator.onLine)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:profile}=await supabase.from("baby_profiles").select("avatar_path").eq("user_id",user.id).maybeSingle();if(profile?.avatar_path){const{data:blob}=await supabase.storage.from("baby-avatars").download(profile.avatar_path);if(blob)setAvatar(URL.createObjectURL(blob))}const pending=readLocal(pendingKey);if(pending.length){const rows=pending.map(({localId,time,asset,id,...m})=>({...m,user_id:user.id,eaten_at:new Date(`2026-07-13T${time}:00+02:00`).toISOString(),emoji:"🥄"}));const{error}=await supabase.from("meals").insert(rows);if(!error)localStorage.removeItem(pendingKey)}const start=new Date("2026-07-13T00:00:00+02:00").toISOString();const{data}=await supabase.from("meals").select("*").gte("eaten_at",start).order("eaten_at");if(data?.length){const next=data.map(m=>({...m,asset:assetFor(m.food)}));setMeals(next);localStorage.setItem(cacheKey,JSON.stringify(next))}};
useEffect(()=>{sync();const on=()=>{setOnline(true);sync();setNotice("已恢复网络，记录已同步")},off=()=>{setOnline(false);setNotice("已进入离线模式，记录会稍后同步")};window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
const addMeal=async record=>{const local={...record,id:`local-${Date.now()}`,localId:Date.now(),eaten_at:`2026-07-13T${record.time}:00+02:00`,asset:assetFor(record.food)};const updated=[...meals,local].sort((a,b)=>new Date(a.eaten_at)-new Date(b.eaten_at));setMeals(updated);localStorage.setItem(cacheKey,JSON.stringify(updated));setSheetOpen(false);if(!navigator.onLine){localStorage.setItem(pendingKey,JSON.stringify([...readLocal(pendingKey),local]));setNotice("已离线保存，联网后自动同步");return}const{data:{user}}=await supabase.auth.getUser();if(!user){localStorage.setItem(pendingKey,JSON.stringify([...readLocal(pendingKey),local]));setAuthOpen(true);setNotice("已保存在手机，登录后同步");return}const{error}=await supabase.from("meals").insert({user_id:user.id,food:record.food,amount_grams:record.amount_grams,eaten_at:local.eaten_at,reaction:record.reaction,note:record.note,emoji:"🥄"});setNotice(error?"已保存在手机，稍后自动重试":"这一餐已同步给家人")};
const changeAvatar=async event=>{const file=event.target.files?.[0];if(!file)return;try{const{blob,dataUrl}=await prepareAvatar(file);setAvatar(dataUrl);localStorage.setItem(avatarKey,dataUrl);if(!navigator.onLine){setNotice("头像已保存在手机，联网登录后可同步");return}const{data:{user}}=await supabase.auth.getUser();if(!user){setAuthOpen(true);setNotice("头像已保存在手机，登录后可同步");return}const path=`${user.id}/elnaz-avatar.webp`;const{error:uploadError}=await supabase.storage.from("baby-avatars").upload(path,blob,{contentType:"image/webp",upsert:true});if(uploadError)throw uploadError;const{error:profileError}=await supabase.from("baby_profiles").upsert({user_id:user.id,baby_name:"Elnaz",avatar_path:path,updated_at:new Date().toISOString()});if(profileError)throw profileError;setNotice("Elnaz 的头像已同步给家人")}catch{setNotice("头像保存失败，请换一张图片重试")}};
return <div className="app-shell"><div className="mobile-prototype"><main className="content"><Header online={online} onCalendar={()=>setNotice("日历视图即将打开")}/><button className="primary-action" onClick={()=>setSheetOpen(true)}><Plus size={25}/>记录一餐</button><HealthStrip/><div className="daily-summary"><Check/><span>今天已吃 {meals.length} 餐 · 共 {total} 克 · 暂无异常</span></div><MealTimeline meals={meals}/><section className="next-food"><div className="next-title"><span><Sparkles/>下一种可以尝试</span><button>为什么推荐 <ChevronRight size={15}/></button></div><div className="next-body"><img src="/assets/pumpkin.png" alt="南瓜"/><div><h2>南瓜泥</h2><p>细腻香甜，富含 β-胡萝卜素。</p><small>建议 10–15克 · 上午尝试</small></div><button aria-label="加入计划"><Plus/></button></div></section><section className="allergy-note"><AlertTriangle/><div><h2>关注宝宝反应</h2><p>首次尝试新食物，建议观察 2–3 天；如出现不适，请暂停并咨询医生。</p></div><button>了解更多 <ChevronRight/></button></section></main><nav className="bottom-nav">{[[CalendarDays,"今天"],[Library,"食物库"],[ClipboardList,"计划"],[Sprout,"成长"]].map(([Icon,label],i)=><button className={i===0?"active":""} key={label}><Icon/><span>{label}</span></button>)}</nav><AnimatePresence>{notice&&<motion.div className="toast" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0}} onAnimationComplete={()=>setTimeout(()=>setNotice(""),2200)}>{notice}</motion.div>}</AnimatePresence></div><aside className="desktop-companion"><span>宝贝食光</span><h1>把每一口成长，<br/>安心地记在一起。</h1><p>专为父母共同使用的宝宝辅食日记。</p><div><ShieldCheck/>云端同步与离线记录</div></aside><AddMealDialog open={sheetOpen} onOpenChange={setSheetOpen} onSave={addMeal}/><AuthDialog open={authOpen} onSignedIn={()=>{setAuthOpen(false);sync()}}/></div>}
export{App};
