// 食物库数据，来源：cuisinez-pour-bebe.fr《Introduction des aliments par âge》
// months = 推荐添加月龄（绿勺）；tryMonths = 可少量尝试月龄（橙勺）；season = 法国应季月份
export const FOOD_CATS = ["蔬菜", "水果", "主食", "蛋白质", "其他"];

const V = "蔬菜", F = "水果", S = "主食", P = "蛋白质", D = "其他";

export const FOOD_LIBRARY = [
  /* ---------- 蔬菜 Légumes ---------- */
  { name: "胡萝卜", fr: "Carotte", emoji: "🥕", cat: V, months: 4, season: "全年", amount: "10–30克", tip: "蒸软打泥，接受度最高的入门蔬菜之一。" },
  { name: "西葫芦", fr: "Courgette", emoji: "🥒", cat: V, months: 4, season: "5–9月", amount: "10–30克", tip: "去皮去籽蒸软，清淡不易过敏。" },
  { name: "西兰花", fr: "Brocoli", emoji: "🥦", cat: V, months: 4, season: "6–11月", amount: "10–30克", tip: "只取花冠蒸软打泥。" },
  { name: "四季豆", fr: "Haricots verts", emoji: "🫛", cat: V, months: 4, season: "7–9月", amount: "10–30克", tip: "去筋煮软，打成细泥。" },
  { name: "菠菜", fr: "Épinards", emoji: "🥬", cat: V, months: 4, season: "9月–6月", amount: "10–30克", tip: "只用叶子，焯水后打泥。" },
  { name: "南瓜", fr: "Potiron", emoji: "🎃", cat: V, months: 4, season: "10–1月", amount: "10–30克", tip: "细腻香甜，富含 β-胡萝卜素。", asset: "/assets/pumpkin.png" },
  { name: "栗子南瓜", fr: "Potimarron", emoji: "🎃", cat: V, months: 4, season: "9–12月", amount: "10–30克", tip: "带栗子香味的小南瓜，蒸软即成泥。" },
  { name: "大南瓜", fr: "Citrouille", emoji: "🎃", cat: V, months: 4, season: "9–12月", amount: "10–30克", tip: "水分多、口感温和。" },
  { name: "红薯", fr: "Patate douce", emoji: "🍠", cat: V, months: 4, season: "全年", amount: "15–30克", tip: "自带甜味，宝宝普遍很喜欢。" },
  { name: "土豆", fr: "Pomme de terre", emoji: "🥔", cat: V, months: 4, season: "全年", amount: "15–30克", tip: "绵软好消化，可作各种蔬菜泥的底。" },
  { name: "豌豆", fr: "Petits pois", emoji: "🫛", cat: V, months: 4, season: "5–6月", amount: "10–30克", tip: "过筛去皮口感更细腻。" },
  { name: "韭葱", fr: "Poireau", emoji: "🥬", cat: V, months: 4, season: "9–4月", amount: "10–20克", tip: "只用葱白，煮软打泥，法式浓汤常客。" },
  { name: "茄子", fr: "Aubergine", emoji: "🍆", cat: V, months: 4, season: "6–9月", amount: "10–30克", tip: "去皮蒸软，口感软滑。" },
  { name: "黄瓜", fr: "Concombre", emoji: "🥒", cat: V, months: 4, season: "4–10月", amount: "10–20克", tip: "去皮去籽，可以生打成泥。" },
  { name: "甜菜根", fr: "Betterave", emoji: "🥗", cat: V, months: 4, season: "10–3月", amount: "10–20克", tip: "颜色鲜艳味道甜，注意会把便便染红，别担心。" },
  { name: "莙荙菜", fr: "Blette", emoji: "🥬", cat: V, months: 4, season: "6–11月", amount: "10–20克", tip: "法国常见叶菜，取嫩叶煮软打泥。" },
  { name: "根芹", fr: "Céleri-rave", emoji: "🥗", cat: V, months: 4, season: "10–3月", amount: "10–20克", tip: "口感像土豆带芹香，蒸软打泥。" },
  { name: "苦苣", fr: "Endive", emoji: "🥬", cat: V, months: 4, season: "10–4月", amount: "10–20克", tip: "煮熟后微苦变甜，少量尝试。" },
  { name: "球茎茴香", fr: "Fenouil", emoji: "🌿", cat: V, months: 4, season: "5–12月", amount: "10–20克", tip: "淡淡茴香甜味，煮软打泥。" },
  { name: "芜菁", fr: "Navet", emoji: "🥗", cat: V, months: 4, season: "10–5月", amount: "10–20克", tip: "法式炖菜常客，煮软后很温和。" },
  { name: "欧防风", fr: "Panais", emoji: "🥕", cat: V, months: 4, season: "10–2月", amount: "10–20克", tip: "像白色胡萝卜，甜味更浓。" },
  { name: "芜菁甘蓝", fr: "Rutabaga", emoji: "🥗", cat: V, months: 4, season: "10–4月", amount: "10–20克", tip: "冬季根茎菜，蒸软打泥。" },
  { name: "生菜", fr: "Salade", emoji: "🥬", cat: V, months: 4, season: "全年", amount: "10–20克", tip: "煮软后少量加进蔬菜泥。" },
  { name: "菊芋", fr: "Topinambour", emoji: "🥔", cat: V, months: 4, season: "11–4月", amount: "10–20克", tip: "洋姜，甜味特别，容易胀气，少量开始。" },
  { name: "牛油果", fr: "Avocat", emoji: "🥑", cat: V, months: 6, tryMonths: 4, season: "10–4月", amount: "15–30克", tip: "健康脂肪丰富，直接压泥即可。" },
  { name: "朝鲜蓟", fr: "Artichaut", emoji: "🌿", cat: V, months: 6, tryMonths: 4, season: "3–9月", amount: "10–20克", tip: "只用芯的部分，煮软打泥。" },
  { name: "西芹", fr: "Céleri-branche", emoji: "🥬", cat: V, months: 6, tryMonths: 4, season: "7–1月", amount: "10–20克", tip: "味道偏浓，少量加进杂蔬泥。" },
  { name: "蘑菇", fr: "Champignon", emoji: "🍄", cat: V, months: 6, tryMonths: 4, season: "全年", amount: "10–20克", tip: "选口蘑等常见蘑菇，煮熟切碎。" },
  { name: "飞碟瓜", fr: "Pâtisson", emoji: "🥒", cat: V, months: 6, tryMonths: 4, season: "7–11月", amount: "10–20克", tip: "南瓜家族，做法同西葫芦。" },
  { name: "彩椒", fr: "Poivron", emoji: "🫑", cat: V, months: 6, tryMonths: 4, season: "6–9月", amount: "10–20克", tip: "去皮去籽蒸软，红黄椒更甜。" },
  { name: "小萝卜", fr: "Radis", emoji: "🥗", cat: V, months: 6, tryMonths: 4, season: "3–6月", amount: "10–20克", tip: "煮熟后辣味消失，少量尝试。" },
  { name: "婆罗门参", fr: "Salsifis", emoji: "🥗", cat: V, months: 6, tryMonths: 4, season: "10–3月", amount: "10–20克", tip: "法国冬季蔬菜，口感细腻微甜。" },
  { name: "番茄", fr: "Tomate", emoji: "🍅", cat: V, months: 6, tryMonths: 4, season: "5–9月", amount: "10–30克", tip: "去皮去籽，煮熟后酸味更柔和。" },
  { name: "白卷心菜", fr: "Chou blanc", emoji: "🥬", cat: V, months: 9, tryMonths: 4, season: "10–4月", amount: "10–20克", tip: "卷心菜类易胀气，9个月后再正式加。" },
  { name: "绿卷心菜", fr: "Chou vert", emoji: "🥬", cat: V, months: 9, tryMonths: 4, season: "10–4月", amount: "10–20克", tip: "煮透后切碎，少量开始。" },
  { name: "紫甘蓝", fr: "Chou rouge", emoji: "🥬", cat: V, months: 9, tryMonths: 4, season: "10–4月", amount: "10–20克", tip: "颜色漂亮，煮软后少量尝试。" },
  { name: "花菜", fr: "Chou-fleur", emoji: "🥦", cat: V, months: 9, tryMonths: 4, season: "9–4月", amount: "10–20克", tip: "只取花冠蒸软，易胀气所以晚些加。" },
  { name: "抱子甘蓝", fr: "Chou de Bruxelles", emoji: "🥬", cat: V, months: 9, tryMonths: 4, season: "9–3月", amount: "10–20克", tip: "煮透去苦味，切碎少量给。" },
  { name: "苤蓝", fr: "Chou-rave", emoji: "🥗", cat: V, months: 9, tryMonths: 4, season: "3–11月", amount: "10–20克", tip: "口感清甜，煮软后尝试。" },
  { name: "洋葱", fr: "Oignon", emoji: "🧅", cat: V, months: 9, tryMonths: 4, season: "9–4月", amount: "5–10克", tip: "煮透变甜，作调味加进菜泥。" },

  /* ---------- 水果 Fruits ---------- */
  { name: "苹果", fr: "Pomme", emoji: "🍎", cat: F, months: 4, season: "9–5月", amount: "15–30克", tip: "蒸熟打泥，口感温和接受度高。", asset: "/assets/apple-puree.png" },
  { name: "香蕉", fr: "Banane", emoji: "🍌", cat: F, months: 4, season: "全年", amount: "15–30克", tip: "选熟透的直接压泥，无需加热。" },
  { name: "梨", fr: "Poire", emoji: "🍐", cat: F, months: 4, season: "全年", amount: "15–30克", tip: "水分足，便秘时可以适量多吃。" },
  { name: "桃子", fr: "Pêche", emoji: "🍑", cat: F, months: 4, season: "6–8月", amount: "15–30克", tip: "去皮去核，熟透的直接压泥。" },
  { name: "油桃", fr: "Nectarine", emoji: "🍑", cat: F, months: 4, season: "6–8月", amount: "15–30克", tip: "做法同桃子，选熟软的。" },
  { name: "杏", fr: "Abricot", emoji: "🍑", cat: F, months: 4, season: "6–8月", amount: "15–30克", tip: "熟透去核压泥，微酸香甜。" },
  { name: "李子", fr: "Prune", emoji: "🍑", cat: F, months: 4, season: "7–10月", amount: "15–30克", tip: "去皮去核，通便效果好。" },
  { name: "紫李", fr: "Quetsche", emoji: "🍇", cat: F, months: 4, season: "8–10月", amount: "15–30克", tip: "法国紫李，做法同李子。" },
  { name: "黄香李", fr: "Mirabelle", emoji: "🍒", cat: F, months: 4, season: "8–9月", amount: "15–30克", tip: "法国特产小黄李，香甜可口。" },
  { name: "西梅干", fr: "Pruneau", emoji: "🍇", cat: F, months: 4, season: "全年", amount: "10–20克", tip: "泡软打泥，便秘小帮手。" },
  { name: "芒果", fr: "Mangue", emoji: "🥭", cat: F, months: 4, season: "4–7月/12月", amount: "15–30克", tip: "熟透的直接压泥。" },
  { name: "甜瓜", fr: "Melon", emoji: "🍈", cat: F, months: 4, season: "6–9月", amount: "15–30克", tip: "去皮去籽，压成泥或小碎块。" },
  { name: "西瓜", fr: "Pastèque", emoji: "🍉", cat: F, months: 4, season: "6–8月", amount: "15–30克", tip: "去籽压碎，水分很足。" },
  { name: "橙子", fr: "Orange", emoji: "🍊", cat: F, months: 4, season: "12–4月", amount: "15–30克", tip: "取果肉去膜去籽，压碎给。" },
  { name: "橘子", fr: "Mandarine", emoji: "🍊", cat: F, months: 4, season: "11–1月", amount: "15–30克", tip: "去膜去籽，切小块。" },
  { name: "小柑橘", fr: "Clémentine", emoji: "🍊", cat: F, months: 4, season: "11–1月", amount: "15–30克", tip: "法国冬天最常见的小橘子。" },
  { name: "西柚", fr: "Pamplemousse", emoji: "🍊", cat: F, months: 4, season: "12–3月", amount: "10–20克", tip: "偏酸，少量尝试。" },
  { name: "柠檬", fr: "Citron", emoji: "🍋", cat: F, months: 4, season: "2–9月", amount: "少量", tip: "几滴柠檬汁调味即可，很酸。" },
  { name: "猕猴桃", fr: "Kiwi", emoji: "🥝", cat: F, months: 6, tryMonths: 4, season: "11–5月", amount: "15–30克", tip: "熟透压泥，个别宝宝口周会发红，注意观察。" },
  { name: "木瓜", fr: "Papaye", emoji: "🥭", cat: F, months: 4, season: "10–12月", amount: "15–30克", tip: "熟透的直接压泥。" },
  { name: "柿子", fr: "Kaki", emoji: "🍅", cat: F, months: 4, season: "10–1月", amount: "15–30克", tip: "一定选完全熟软的，挖果肉压泥。" },
  { name: "榅桲", fr: "Coing", emoji: "🍐", cat: F, months: 4, season: "10月", amount: "15–30克", tip: "必须煮熟才能吃，煮后香气特别。" },
  { name: "葡萄", fr: "Raisin", emoji: "🍇", cat: F, months: 4, season: "7–10月", amount: "15–30克", tip: "去皮去籽压扁，整颗有呛噎风险。" },
  { name: "草莓", fr: "Fraise", emoji: "🍓", cat: F, months: 6, tryMonths: 4, season: "4–6月", amount: "15–30克", tip: "压碎给，第一次少量观察皮肤反应。" },
  { name: "树莓", fr: "Framboise", emoji: "🍓", cat: F, months: 6, tryMonths: 4, season: "7–9月", amount: "10–20克", tip: "压碎过筛去籽更细腻。" },
  { name: "蓝莓", fr: "Myrtille", emoji: "🫐", cat: F, months: 6, tryMonths: 4, season: "6–9月", amount: "10–20克", tip: "压扁或切半，避免整颗。" },
  { name: "黑莓", fr: "Mûre", emoji: "🫐", cat: F, months: 6, tryMonths: 4, season: "7–10月", amount: "10–20克", tip: "压碎过筛去籽。" },
  { name: "黑加仑", fr: "Cassis", emoji: "🫐", cat: F, months: 6, tryMonths: 4, season: "8–9月", amount: "10–20克", tip: "偏酸，可混进其他果泥。" },
  { name: "红醋栗", fr: "Groseille", emoji: "🍒", cat: F, months: 6, tryMonths: 4, season: "6–9月", amount: "10–20克", tip: "酸味明显，少量混合着给。" },
  { name: "樱桃", fr: "Cerise", emoji: "🍒", cat: F, months: 6, tryMonths: 4, season: "6月", amount: "10–20克", tip: "去核压碎，务必去干净核。" },
  { name: "菠萝", fr: "Ananas", emoji: "🍍", cat: F, months: 6, tryMonths: 4, season: "10–4月", amount: "10–20克", tip: "取最软的部分打泥，偏酸。" },
  { name: "荔枝", fr: "Litchi", emoji: "🍇", cat: F, months: 6, tryMonths: 4, season: "11–1月", amount: "10–20克", tip: "去核切碎，很甜所以少量。" },
  { name: "无花果", fr: "Figue", emoji: "🍇", cat: F, months: 6, tryMonths: 4, season: "7–10月", amount: "15–30克", tip: "熟透的去皮压泥。" },
  { name: "石榴", fr: "Grenade", emoji: "🍎", cat: F, months: 6, tryMonths: 4, season: "11–2月", amount: "10–20克", tip: "取汁或压碎过筛，籽不能整颗给。" },
  { name: "百香果", fr: "Fruit de la passion", emoji: "🍈", cat: F, months: 6, tryMonths: 4, season: "全年", amount: "少量", tip: "过筛去籽取汁，偏酸。" },
  { name: "椰枣", fr: "Datte", emoji: "🌴", cat: F, months: 9, tryMonths: 4, season: "10–12月", amount: "5–10克", tip: "很甜，去核泡软后少量。" },
  { name: "大黄", fr: "Rhubarbe", emoji: "🌿", cat: F, months: 6, tryMonths: 4, season: "4–7月", amount: "10–20克", tip: "只吃茎，必须煮熟，偏酸可配苹果。" },
  { name: "栗子", fr: "Châtaigne", emoji: "🌰", cat: F, months: 6, tryMonths: 4, season: "10月", amount: "10–20克", tip: "煮熟打成细泥，香甜绵密。" },
  { name: "杏仁", fr: "Amande", emoji: "🌰", cat: F, months: 6, tryMonths: 4, season: "9–10月", amount: "少量", tip: "只给细粉或杏仁酱，坚果注意过敏，观察3天。" },
  { name: "榛子", fr: "Noisette", emoji: "🌰", cat: F, months: 6, tryMonths: 4, season: "9–11月", amount: "少量", tip: "只给细粉或坚果酱，注意过敏。" },
  { name: "核桃", fr: "Noix", emoji: "🌰", cat: F, months: 6, tryMonths: 4, season: "10–11月", amount: "少量", tip: "只给细粉或坚果酱，注意过敏。" },

  /* ---------- 主食 Féculents ---------- */
  { name: "婴儿米粉", fr: "Farine infantile", emoji: "🍚", cat: S, months: 4, amount: "10–30克", tip: "最常见的第一口辅食，选铁强化的。", asset: "/assets/rice-cereal.png" },
  { name: "甜玉米", fr: "Maïs doux", emoji: "🌽", cat: S, months: 4, amount: "15–30克", tip: "煮软打成细泥，过筛去皮。" },
  { name: "燕麦", fr: "Avoine", emoji: "🥣", cat: S, months: 6, tryMonths: 4, amount: "20–40克", tip: "选婴儿燕麦片，煮至软烂。" },
  { name: "小麦面粉", fr: "Blé (farine)", emoji: "🌾", cat: S, months: 6, tryMonths: 4, amount: "适量", tip: "含麸质，建议在6个月左右少量引入。" },
  { name: "面包", fr: "Pain", emoji: "🍞", cat: S, months: 9, tryMonths: 6, amount: "适量", tip: "面包芯或烤脆的面包条，练习抓握。" },
  { name: "意面", fr: "Pâtes", emoji: "🍝", cat: S, months: 9, tryMonths: 6, amount: "30–50克", tip: "选小颗粒意面煮到很软。" },
  { name: "白米饭", fr: "Riz blanc", emoji: "🍚", cat: S, months: 9, tryMonths: 4, amount: "30–60克", tip: "煮得比大人的软烂，或先做成米糊。" },
  { name: "半糙米", fr: "Riz semi-complet", emoji: "🍚", cat: S, months: 9, tryMonths: 6, amount: "30–50克", tip: "纤维多一些，煮软烂再给。" },
  { name: "玉米糊", fr: "Polenta", emoji: "🌽", cat: S, months: 9, tryMonths: 4, amount: "20–40克", tip: "意式玉米糊，煮稠后口感绵密。" },
  { name: "藜麦", fr: "Quinoa", emoji: "🌾", cat: S, months: 9, tryMonths: 4, amount: "20–40克", tip: "冲洗后煮至开花，蛋白质丰富。" },
  { name: "荞麦", fr: "Sarrasin", emoji: "🌾", cat: S, months: 9, tryMonths: 4, amount: "20–40克", tip: "无麸质，法国可丽饼原料。" },
  { name: "粗麦粉", fr: "Semoule, boulgour", emoji: "🌾", cat: S, months: 9, tryMonths: 4, amount: "20–40克", tip: "煮软后像小米糊，含麸质。" },
  { name: "木薯粉", fr: "Tapioca", emoji: "🥣", cat: S, months: 9, tryMonths: 4, amount: "15–30克", tip: "煮成布丁状，好消化。" },
  { name: "红扁豆", fr: "Lentilles corail", emoji: "🫘", cat: S, months: 12, tryMonths: 4, amount: "20–40克", tip: "豆类易胀气，煮烂过筛，1岁后正式加。" },
  { name: "绿扁豆", fr: "Lentilles vertes", emoji: "🫘", cat: S, months: 12, tryMonths: 4, amount: "20–40克", tip: "煮烂过筛去皮，1岁后正式加。" },
  { name: "鹰嘴豆", fr: "Pois chiches", emoji: "🫘", cat: S, months: 12, tryMonths: 4, amount: "20–40克", tip: "煮烂打泥（像鹰嘴豆泥），1岁后正式加。" },
  { name: "白芸豆", fr: "Haricots blancs", emoji: "🫘", cat: S, months: 12, tryMonths: 4, amount: "20–40克", tip: "煮烂去皮打泥，1岁后正式加。" },
  { name: "红芸豆", fr: "Haricots rouges", emoji: "🫘", cat: S, months: 12, tryMonths: 4, amount: "20–40克", tip: "必须彻底煮熟，1岁后正式加。" },
  { name: "蚕豆", fr: "Fèves", emoji: "🫘", cat: S, months: 12, tryMonths: 4, amount: "20–40克", tip: "去皮煮烂，1岁后正式加。" },

  /* ---------- 蛋白质 Protéines ---------- */
  { name: "鸡蛋", fr: "Oeuf", emoji: "🥚", cat: P, months: 6, tryMonths: 4, amount: "6–9月 ¼个 · 12月 ⅓个", tip: "全蛋煮熟，从一小勺开始，观察3天。" },
  { name: "白肉", fr: "Viande blanche", emoji: "🍗", cat: P, months: 6, tryMonths: 4, amount: "6月10克 · 9月15克 · 12月20克", tip: "鸡肉/火鸡，煮熟打成细泥，每日中午为宜。" },
  { name: "红肉", fr: "Viande rouge", emoji: "🥩", cat: P, months: 6, tryMonths: 4, amount: "6月10克 · 9月15克 · 12月20克", tip: "牛肉/猪肉，补铁好帮手，务必全熟打泥。" },
  { name: "白身鱼", fr: "Poisson maigre", emoji: "🐟", cat: P, months: 6, tryMonths: 4, amount: "6月10克 · 9月15克 · 12月20克", tip: "鳕鱼/鲈鱼等，蒸熟挑净刺压碎。" },
  { name: "油性鱼", fr: "Poisson gras", emoji: "🐟", cat: P, months: 6, tryMonths: 4, amount: "6月10克 · 9月15克 · 12月20克", tip: "三文鱼/沙丁鱼，富含DHA，挑净刺。" },
  { name: "海鲜", fr: "Fruits de mer (cuits)", emoji: "🦐", cat: P, months: 6, tryMonths: 4, amount: "6月10克 · 9月15克 · 12月20克", tip: "必须彻底煮熟，切碎，注意过敏。" },
  { name: "加工肉制品", fr: "Charcuterie", emoji: "🌭", cat: P, months: 36, amount: "—", tip: "火腿香肠等，含盐高，3岁前不建议。" },

  /* ---------- 其他 Divers ---------- */
  { name: "酸奶", fr: "Yaourt", emoji: "🥛", cat: D, months: 6, tryMonths: 4, amount: "30–60克", tip: "选无糖全脂原味，母乳/配方奶仍是主角。" },
  { name: "奶酪", fr: "Fromage pasteurisé", emoji: "🧀", cat: D, months: 6, tryMonths: 4, amount: "10–20克", tip: "只选巴氏杀菌奶酪；生奶奶酪5岁前不要。" },
  { name: "香草香料", fr: "Herbes et épices", emoji: "🌿", cat: D, months: 6, amount: "少量", tip: "罗勒、肉桂等温和香料，让味觉更丰富。" },
  { name: "蜂蜜", fr: "Miel", emoji: "🍯", cat: D, months: 12, amount: "少量", tip: "1岁前绝对不能吃（肉毒杆菌风险）！" },
  { name: "巧克力", fr: "Chocolat", emoji: "🍫", cat: D, months: 12, amount: "少量", tip: "1岁后偶尔一点点就好。" },
  { name: "生奶奶酪", fr: "Fromage au lait cru", emoji: "🧀", cat: D, months: 60, amount: "—", tip: "未经巴氏杀菌，5岁前不要吃。" },
];
